src/AppBundle/Entity/Search.php
<?php

namespace Thepixeldeveloper\Nolimitsexchange\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Search.
 *
 * @ORM\Table(name="search")
 * @ORM\Entity(readOnly=true, repositoryClass="Thepixeldeveloper\Nolimitsexchange\AppBundle\Repository\SearchRepository")
 */
class Search
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\Column(name="id", type="integer", length=8, nullable=false)
     */
    protected $id;

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer", length=1, nullable=false)
     */
    protected $status;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=245, nullable=false)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(name="rating", type="float", length=4, nullable=false, precision=2)
     */
    protected $rating;

    /**
     * @var int
     *
     * @ORM\Column(name="downloads", type="integer", length=8, nullable=false)
     */
    protected $downloads;

    /**
     * @var int
     *
     * @ORM\Column(name="user_id", type="integer", length=11, nullable=false)
     */
    protected $userId;

    /**
     * @var string
     *
     * @ORM\Column(name="user_username", type="string", length=255, nullable=false)
     */
    protected $userUsername;

    /**
     * @var int
     *
     * @ORM\Column(name="style_id", type="integer", length=8, nullable=false)
     */
    protected $styleId;

    /**
     * @var string
     *
     * @ORM\Column(name="style_name", type="string", length=255, nullable=false)
     */
    protected $styleName;

    /**
     * @var string
     *
     * @ORM\Column(name="style_short", type="string", length=50, nullable=false)
     */
    protected $styleShort;

    /**
     * @var string
     *
     * @ORM\Column(name="screenshot_ext", type="string", length=4, nullable=false)
     */
    private $screenshotExt;

    /**
     * @var string
     *
     * @ORM\Column(name="coaster_ext", type="string", length=8, nullable=false)
     */
    private $coasterExt;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @return int
     */
    public function getDownloads()
    {
        return $this->downloads;
    }

    /**
     * @return int
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * @return string
     */
    public function getUserUsername()
    {
        return $this->userUsername;
    }

    /**
     * @return int
     */
    public function getStyleId()
    {
        return $this->styleId;
    }

    /**
     * @return string
     */
    public function getStyleName()
    {
        return $this->styleName;
    }

    /**
     * @return string
     */
    public function getStyleShort()
    {
        return $this->styleShort;
    }

    /**
     * @return string
     */
    public function getScreenshotExt(): string
    {
        return $this->screenshotExt;
    }

    /**
     * @return string
     */
    public function getCoasterExt(): string
    {
        return $this->coasterExt;
    }
}

src/AppBundle/Entity/SearchTypes.php
<?php

namespace Thepixeldeveloper\Nolimitsexchange\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Search.
 *
 * @ORM\Table(name="search_types")
 * @ORM\Entity(readOnly=true, repositoryClass="Thepixeldeveloper\Nolimitsexchange\AppBundle\Repository\SearchTypesRepository")
 */
class SearchTypes
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\Column(name="id", type="integer", length=8, nullable=false)
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    protected $name;

    /**
     * @var int
     *
     * @ORM\Column(name="version", type="integer", length=11, nullable=false)
     */
    protected $version;

    /**
     * @var int
     *
     * @ORM\Column(name="count", type="integer", length=11, nullable=false)
     */
    protected $count;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Get version as a string.
     *
     * @return string
     */
    public function getVersionAsString(): string
    {
        $map = [
            1 => 'NL1',
            2 => 'NL2',
        ];

        return $map[$this->getVersion()];
    }

    /**
     * Get name with count in parenthesis.
     *
     * @return string
     */
    public function getNameWithCounts(): string
    {
        return sprintf('%s (%d)', $this->getName(), $this->getCount());
    }
}

src/AppBundle/Form/Search.php
<?php

namespace Thepixeldeveloper\Nolimitsexchange\AppBundle\Form;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Search
 *
 * @package Thepixeldeveloper\Nolimitsexchange\AppBundle\Form
 */
class Search
{
    /**
     * @var string
     * @Assert\Type(type="string")
     */
    protected $term;
    
    /**
     * @var string
     * @Assert\Type(type="string")
     */
    protected $author;

    /**
     * @Assert\Type(type="integer")
     */
    protected $type;

    /**
     * @Assert\Type(type="integer")
     */
    protected $downloadsFrom;

    /**
     * @Assert\Type(type="integer")
     */
    protected $downloadsTo;

    /**
     * @Assert\Type(type="integer")
     */
    protected $ratingsFrom;

    /**
     * @Assert\Type(type="integer")
     */
    protected $ratingsTo;

    /**
     * @Assert\Choice(choices = {"asc", "desc"}, message = "Choose a valid sort direction.")
     */
    protected $downloadsSort;

    /**
     * @Assert\Choice(choices = {"asc", "desc"}, message = "Choose a valid sort direction.")
     */
    protected $ratingsSort;

    /**
     * @return string
     */
    public function getTerm()
    {
        return $this->term;
    }

    /**
     * @param string $term
     */
    public function setTerm($term)
    {
        $this->term = $term;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getDownloadsFrom()
    {
        return $this->downloadsFrom;
    }

    /**
     * @param mixed $downloadsFrom
     */
    public function setDownloadsFrom($downloadsFrom)
    {
        $this->downloadsFrom = $downloadsFrom;
    }

    /**
     * @return mixed
     */
    public function getDownloadsTo()
    {
        return $this->downloadsTo;
    }

    /**
     * @param mixed $downloadsTo
     */
    public function setDownloadsTo($downloadsTo)
    {
        $this->downloadsTo = $downloadsTo;
    }

    /**
     * @return mixed
     */
    public function getRatingsFrom()
    {
        return $this->ratingsFrom;
    }

    /**
     * @param mixed $ratingsFrom
     */
    public function setRatingsFrom($ratingsFrom)
    {
        $this->ratingsFrom = $ratingsFrom;
    }

    /**
     * @return mixed
     */
    public function getRatingsTo()
    {
        return $this->ratingsTo;
    }

    /**
     * @param mixed $ratingsTo
     */
    public function setRatingsTo($ratingsTo)
    {
        $this->ratingsTo = $ratingsTo;
    }

    /**
     * @return mixed
     */
    public function getDownloadsSort()
    {
        return $this->downloadsSort;
    }

    /**
     * @return string
     */
    public function getDownloadsSortInverse()
    {
        if ($sort = $this->getDownloadsSort()) {
            return $this->getSortInverse($sort);
        }
    }

    /**
     * @param mixed $downloadsSort
     */
    public function setDownloadsSort($downloadsSort)
    {
        $this->downloadsSort = $downloadsSort;
    }

    /**
     * @return mixed
     */
    public function getRatingsSort()
    {
        return $this->ratingsSort;
    }

    /**
     * @return string
     */
    public function getRatingsSortInverse()
    {
        if ($sort = $this->getRatingsSort()) {
            return $this->getSortInverse($sort);
        }
    }

    /**
     * @param mixed $ratingsSort
     */
    public function setRatingsSort($ratingsSort)
    {
        $this->ratingsSort = $ratingsSort;
    }

    /**
     * @param string $sort
     *
     * @return string
     */
    protected function getSortInverse(string $sort): string
    {
        return $sort === 'asc' ? 'desc' : 'asc';
    }
    
    /**
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }
    
    /**
     * @param string $author
     */
    public function setAuthor(string $author)
    {
        $this->author = $author;
    }
}

src/AppBundle/Form/Type/SearchType.php
<?php

namespace Thepixeldeveloper\Nolimitsexchange\AppBundle\Form\Type;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Thepixeldeveloper\Nolimitsexchange\AppBundle\Entity\SearchTypes;

class SearchType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'csrf_protection' => false,
        ]);
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->setMethod(Request::METHOD_GET)
            ->add('term', TextType::class, ['required' => false])
            ->add('author', TextType::class, ['required' => false])
            ->add('type', EntityType::class, [
                'class'        => 'AppBundle:SearchTypes',
                'placeholder'  => 'Coaster Type',
                'required'     => false,
                'choice_label' => function(SearchTypes $types) {
                    return $types->getNameWithCounts();
                },
                'group_by' => function(SearchTypes $types) {
                    return $types->getVersionAsString();
                },
            ])
            ->add('submit', SubmitType::class);
    }

    public function getBlockPrefix()
    {
        return null;
    }
}

src/AppBundle/Controller/SearchController.php
<?php

namespace Thepixeldeveloper\Nolimitsexchange\AppBundle\Controller;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Thepixeldeveloper\Nolimitsexchange\AppBundle\Form\Search;
use Thepixeldeveloper\Nolimitsexchange\AppBundle\Form\Type\SearchType;

class SearchController extends Controller
{
    /**
     * @Route("/search/categories.html", name="search_categories_partial")
     * @throws \Symfony\Component\OptionsResolver\Exception\InvalidOptionsException
     */
    public function searchCategoriesPartialAction(Request $request)
    {
        $search = new Search();

        $form = $this->createForm(SearchType::class, $search);
        $form->handleRequest($request);

        return $this->render('AppBundle:Search:categories_partial.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/search", name="search")
     * @Template
     *
     * @param Request $request
     *
     * @return array
     *
     * @throws \LogicException
     */
    public function indexAction(Request $request)
    {
        $search = new Search();
        $search->setDownloadsSort($request->query->get('downloads_sort'));
        $search->setRatingsSort($request->query->get('ratings_sort'));

        $form = $this->createForm(SearchType::class, $search);
        $form->handleRequest($request);
        
        $files = $this
            ->getDoctrine()
            ->getRepository('AppBundle:Search')
            ->search($search);

        $files = new DoctrineORMAdapter($files, false);

        $pager = (new Pagerfanta($files))
            ->setMaxPerPage(10)
            ->setCurrentPage($request->get('page', 1));

        return [
            'title'  => $this->get('translator')->trans('Search'),
            'files'  => $pager->getCurrentPageResults(),
            'form'   => $form->createView(),
            'pager'  => $pager,
        ];
    }
}

src/AppBundle/Resources/views/Search/categories_partial.html.twig
{% form_theme form 'bootstrap_3_layout.html.twig' %}

<div class="panel panel-search">
    <div class="panel-heading">
        <h2>Filters</h2>
    </div>

    <div class="panel-body">
        {{ form_start((form)) }}
        <table class="table table-responsive table-coaster-meta table-search-form">
            <tbody>

            <tr>
                <td>
                {{
                    form_widget(form.term, {
                        'attr': {
                            'class': 'input-lg',
                            'placeholder': 'Search Term'
                        }
                    })
                }}
                </td>
            </tr>
            <tr>
                <td>
                {{
                    form_widget(form.author, {
                        'attr': {
                            'class': 'input-lg',
                            'placeholder': 'Username'
                        }
                    })
                }}
                </td>
            </tr>
            <tr>
                <td>
                    {{
                        form_widget(form.type, {
                            'attr': {
                                'class': 'text',
                            }
                        })
                    }}
                </td>
            </tr>
            <tr>
                <td>
                    {{ form_widget(form.submit, { 'attr': { 'class': 'btn-primary btn-lg btn-block'} }) }}
                </td>
            </tr>
            </tbody>
        </table>
        {{ form_end(form) }}
    </div>
</div>

src/AppBundle/Resources/views/Search/index.html.twig
{% extends '::base.html.twig' %}

{% block title %}Search - Nolimits Exchange{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-3">
            {{ render(controller('AppBundle:Search:searchCategoriesPartial', { request: app.request })) }}
        </div>

        <div class="col-md-9">
            <div class="panel panel-search panel-page">
                <div class="panel-heading">
                    <h1>Search</h1>
                </div>
                <div class="panel-body">
                    <table class="table table-condensed table-responsive table-coasters">
                        <thead>
                        <tr>
                            <th colspan="2"></th>
                            <th>Style</th>
                            <th><a href="{{ path('search', app.request.query | merge({ 'downloads_sort': form.vars.value.downloadsSortInverse | default('desc'), 'ratings_sort': '' })) }}">Downloads</a></th>
                            <th><a href="{{ path('search', app.request.query | merge({ 'ratings_sort': form.vars.value.ratingsSortInverse | default('desc'), 'downloads_sort': '' })) }}">Rating</a></th>
                        </tr>
                        </thead>
                        {% for file in files %}
                            <tr>
                                <td class="coaster-screenshot">
                                    <img src="{{ asset(screenshot_path(file.id, file.screenshotExt, 'thumbnail'), 'screenshots') }}" alt="{{ file.name | e('html_attr') }}">
                                </td>
                                <td>
                                    <a href="{{ url('coaster', {id: file.id, slug: file.name | slugify}) }}" title="{{ file.name }}">
                                        <h4 class="coaster-name">{{ file.name }}</h4>
                                        <p class="author">{{ file.userUsername}}</p>
                                    </a>
                                </td>
                                <td class="coaster-style">
                                    <a href="{{ path('search', app.request.query | merge({ type: file.styleId })) }}">{{ file.styleName }}</a>
                                </td>
                                <td class="coaster-downloads">
                                    <span>{{ file.downloads | number_format }}</span>
                                </td>
                                <td class="rating text-center">
                                    {{ file.rating | number_format(2) }}
                                </td>
                            </tr>
                        {% else %}
                            No results.
                        {% endfor %}
                    </table>
                    <div class="news-pagination">
                        {{ pagerfanta(pager, 'twitter_bootstrap3') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}